name: Firebase Cron

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Access Firebase
        run: curl https://chidimin.github.io/kariya-bus/
