name: Update Bus Data

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch Bus Data
        run: |
          curl -o bus.json https://api-public.odpt.org/api/v4/odpt:Bus

      - name: Commit
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git add .
          git commit -m "update bus data" || exit 0
          git push
        
